### ISSUE TITLE
absl.flags._exceptions.UnrecognizedFlagError: Unknown command line flag 'out_dir'

### ISSUE THREAD

**Issue by vendyv** [allenai/bi-att-flow#119]
This error pops up everytime i try to run 'run-demo.py' from demo branch. 

command: python3 run-demo.py
`Traceback (most recent call last):
  File "run-demo.py", line 16, in <module>
    demo = Demo()
  File "/home/vendy/Desktop/kwgraph/bi-att-flow-demo/basic/demo_cli.py", line 117, in __init__
    config.out_dir = os.path.join(config.out_base_dir, config.model_name, str(config.run_id).zfill(2))
  File "/home/vendy/.local/lib/python3.6/site-packages/tensorflow_core/python/platform/flags.py", line 88, in __setattr__
    return self.__dict__['__wrapped'].__setattr__(name, value)
  File "/home/vendy/.local/lib/python3.6/site-packages/absl/flags/_flagvalues.py", line 499, in __setattr__
    return self._set_unknown_flag(name, value)
  File "/home/vendy/.local/lib/python3.6/site-packages/absl/flags/_flagvalues.py", line 375, in _set_unknown_flag
    raise _exceptions.UnrecognizedFlagError(name, value)
absl.flags._exceptions.UnrecognizedFlagError: Unknown command line flag 'out_dir'`

**Comment by naveenjafer** [comment]
@vendyv Did you manage to get this to work? I am facing the same issue

**Comment by 353xiong** [comment]
add this in cli.py

flags.DEFINE_string("out_dir", "", "")
flags.DEFINE_string("save_dir", "", "")
flags.DEFINE_string("eval_dir", "", "")
flags.DEFINE_string("answer_dir", "", "")
