### ISSUE TITLE
Issues  with save folder 

### ISSUE THREAD

**Issue by chetanchhabra** [allenai/bi-att-flow#121]
I got the error 
FileNotFoundError: [Errno 2] No such file or directory: 'save/37/shared.json'

save file is not available on https://worksheets.codalab.org/worksheets/0x37a9b8c44f6845c28866267ef941c89d/
I find it in out folder on 
https://github.com/allenai/bi-att-flow/releases/tag/v0.3.0

**Comment by kansalaman** [comment]
I am facing the same issue. On running
 `basic/run_single.sh $HOME/data/squad/dev-v1.1.json single.json` I get 

`Traceback (most recent call last):
  File "/usr/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/mnt/blossom/data/amankansal/QA/2020-Hotpot-QA/bi-att-flow/basic/cli.py", line 109, in <module>
    tf.app.run()
  File "/mnt/blossom/data/amankansal/QA/2020-Hotpot-QA/bi-att-flow/bidaf_venv/lib/python3.6/site-packages/tensorflow/python/platform/app.py", line 43, in run
    sys.exit(main(sys.argv[:1] + flags_passthrough))
  File "/mnt/blossom/data/amankansal/QA/2020-Hotpot-QA/bi-att-flow/basic/cli.py", line 106, in main
    m(config)
  File "/mnt/blossom/data/amankansal/QA/2020-Hotpot-QA/bi-att-flow/basic/main.py", line 27, in main
    _forward(config)
  File "/mnt/blossom/data/amankansal/QA/2020-Hotpot-QA/bi-att-flow/basic/main.py", line 177, in _forward
    test_data = read_data(config, config.forward_name, True)
  File "/mnt/blossom/data/amankansal/QA/2020-Hotpot-QA/bi-att-flow/basic/read_data.py", line 206, in read_data
    new_shared = json.load(open(shared_path, 'r'))
FileNotFoundError: [Errno 2] No such file or directory: 'save/37/shared.json'`

Folder `37` is not in save. The only ones are 
`34  35	70  71	72  73	74  75	76  77`

**Comment by naveenjafer** [comment]
@chetanchhabra Any luck on finding what this shared.json file is? I used the one from the out folder, but later ran into shape mismatch errors #113
