### ISSUE TITLE
AttributeError: max_num_sents

### ISSUE THREAD

**Issue by gfrison** [allenai/bi-att-flow#19]
Hello,

on running `basic/run_single.sh ~/data/squad/dev-v1.1.json single.json` I got the following error:
```
Traceback (most recent call last):
  File "/usr/lib/python3.5/runpy.py", line 184, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.5/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/gfrison/ws/bi-att-flow-demo/basic/cli.py", line 109, in <module>
    tf.app.run()
  File "/home/gfrison/.p3/lib/python3.5/site-packages/tensorflow/python/platform/app.py", line 30, in run
    sys.exit(main(sys.argv[:1] + flags_passthrough))
  File "/home/gfrison/ws/bi-att-flow-demo/basic/cli.py", line 106, in main
    m(config)
  File "/home/gfrison/ws/bi-att-flow-demo/basic/main.py", line 27, in main
    _forward(config)
  File "/home/gfrison/ws/bi-att-flow-demo/basic/main.py", line 192, in _forward
    models = get_multi_gpu_models(config)
  File "/home/gfrison/ws/bi-att-flow-demo/basic/model.py", line 19, in get_multi_gpu_models
    model = Model(config, scope, rep=gpu_idx == 0)
  File "/home/gfrison/ws/bi-att-flow-demo/basic/model.py", line 34, in __init__
    config.batch_size, config.max_num_sents, config.max_sent_size, \
  File "/home/gfrison/.p3/lib/python3.5/site-packages/tensorflow/python/platform/flags.py", line 44, in __getattr__
    raise AttributeError(name)
AttributeError: max_num_sents
```

I got it in the demo branch. In the master branch works correctly.
What can I do for making it working?

Thank you

**Comment by seominjoon** [comment]
Hi,
run.single.sh is for test only, and not for demo.
It might not be compatible with demo branch code. Please reopen the issue if this continues to happen in master branch.
