### ISSUE TITLE
ImportError: /usr/local/lib/python3.4/dist-packages/tensorflow/python/_pywrap_tensorflow.so: invalid ELF header

### ISSUE THREAD

**Issue by alphaaurigae** [allenai/bi-att-flow#53]
https://hastebin.com/elejasoqef.sql -- colored output

`OS 14.04
bi-att-flow branch: Master
script that produced the error: (master branch) https://github.com/alphaaurigae/bi-att-flow_bash

BEGIN TRAINING SECTION 2.TRAINING

# 2. Training
# The model has ~2.5M parameters. The model was trained with NVidia Titan X (Pascal Architecture, 2016). The model requires at least 12GB of GPU RAM. If your GPU RAM is smaller than 12GB, you can either decrease batch size (performance might degrade), or you can use multi GPU (see below). The training converges at ~18k steps, and it took ~4s per step (i.e. ~20 hours).

# Before training, it is recommended to first try the following code to verify everything is okay and memory is sufficient:
python3 -m basic.cli --mode train --noload --debug

run python3 -m basic.cli --mode train --noload --debug OR n SKIP??? [Y/n] Y
Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/tensorflow/python/pywrap_tensorflow.py", line 18, in swig_import_helper
    return importlib.import_module(mname)
  File "/usr/lib/python3.4/importlib/__init__.py", line 109, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 2254, in _gcd_import
  File "<frozen importlib._bootstrap>", line 2237, in _find_and_load
  File "<frozen importlib._bootstrap>", line 2226, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 1191, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 1161, in _load_backward_compatible
  File "<frozen importlib._bootstrap>", line 539, in _check_name_wrapper
  File "<frozen importlib._bootstrap>", line 1715, in load_module
  File "<frozen importlib._bootstrap>", line 321, in _call_with_frames_removed
ImportError: /usr/local/lib/python3.4/dist-packages/tensorflow/python/_pywrap_tensorflow.so: invalid ELF header

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.4/runpy.py", line 170, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.4/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/hus/github/bi-att-flow/allenai/bi-att-flow/basic/cli.py", line 3, in <module>
    import tensorflow as tf
  File "/usr/local/lib/python3.4/dist-packages/tensorflow/__init__.py", line 23, in <module>
    from tensorflow.python import *
  File "/usr/local/lib/python3.4/dist-packages/tensorflow/python/__init__.py", line 49, in <module>
    from tensorflow.python import pywrap_tensorflow
  File "/usr/local/lib/python3.4/dist-packages/tensorflow/python/pywrap_tensorflow.py", line 21, in <module>
    _pywrap_tensorflow = swig_import_helper()
  File "/usr/local/lib/python3.4/dist-packages/tensorflow/python/pywrap_tensorflow.py", line 20, in swig_import_helper
    return importlib.import_module('_pywrap_tensorflow')
  File "/usr/lib/python3.4/importlib/__init__.py", line 109, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
ImportError: No module named '_pywrap_tensorflow'

# Then to fully train, run:
python3 -m basic.cli --mode train --noload

run python3 -m basic.cli --mode train --noload OR n SKIP??? [Y/n] ^C

`

**Comment by guotong1988** [comment]
it seems tensorflow does not support python 3.4
You can try python 3.5 or 3.6

**Comment by guotong1988** [comment]
It seems it is a tensorflow installation problem.
You can try to google it.

**Comment by alphaaurigae** [comment]
thx for your reply. Ill get back to it by tomorrow. It also  turned out the
14.04 i had to work on was very much out of date to my surprise.
