### ISSUE TITLE
_linear() got an unexpected keyword argument 'bias_start'

### ISSUE THREAD

**Issue by st474ddr** [allenai/bi-att-flow#93]
Excuse me,
I got a TypeError:_linear() got an unexpected keyword argument 'bias_start'
please help me ~

**Comment by Vimos** [comment]
My suggestion is we insert a new `_linear` function here:

```

def _linear(args, output_size, bias, bias_start=0.0, scope=None):
    """Linear map: sum_i(args[i] * W[i]), where W[i] is a variable.

    Args:
      args: a 2D Tensor or a list of 2D, batch x n, Tensors.
      output_size: int, second dimension of W[i].
      bias: boolean, whether to add a bias term or not.
      bias_start: starting value to initialize the bias; 0 by default.
      scope: (optional) Variable scope to create parameters in.

    Returns:
      A 2D Tensor with shape [batch x output_size] equal to
      sum_i(args[i] * W[i]), where W[i]s are newly created matrices.

    Raises:
      ValueError: if some of the arguments has unspecified or wrong shape.
    """
    if args is None or (nest.is_sequence(args) and not args):
        raise ValueError("`args` must be specified")
    if not nest.is_sequence(args):
        args = [args]

    # Calculate the total size of arguments on dimension 1.
    total_arg_size = 0
    shapes = [a.get_shape() for a in args]
    for shape in shapes:
        if shape.ndims != 2:
            raise ValueError("linear is expecting 2D arguments: %s" % shapes)
        if shape[1].value is None:
            raise ValueError("linear expects shape[1] to be provided for shape %s, "
                             "but saw %d" % (shape, shape[1]))
        else:
            total_arg_size += shape[1].value

    dtype = [a.dtype for a in args][0]

    # Now the computation.
    scope = scope or vs.get_variable_scope()
    with vs.variable_scope(scope) as outer_scope:
        weights = vs.get_variable(
            "weights", [total_arg_size, output_size], dtype=dtype)
        if len(args) == 1:
            res = math_ops.matmul(args[0], weights)
        else:
            res = math_ops.matmul(array_ops.concat(args, 1), weights)
        if not bias:
            return res
        with vs.variable_scope(outer_scope) as inner_scope:
            inner_scope.set_partitioner(None)
            biases = vs.get_variable(
                "biases", [output_size],
                dtype=dtype,
                initializer=init_ops.constant_initializer(bias_start, dtype=dtype))
    return nn_ops.bias_add(res, biases)
```

**Comment by WangJiuniu** [comment]
I meet the same problem when I try to use tensorflow==1.3.0.  The problem is saved when I change it to the version guided.
Good luck!

**Comment by aneesh-joshi** [comment]
Unfortunately, this repo only supports tf 0.11 which had another definition of _linear.
It's location and definition has since changed.
I tried a lot to port it to 1.3 but to no avail.
Did you find any solution?
@st474ddr @WangJiuniu

**Comment by Vimos** [comment]
@aneesh-joshi , maybe you can give my branch [Tf1.8](https://github.com/Vimos/bi-att-flow/tree/tf1.8) a try, I was able to run it last month.

**Comment by aneesh-joshi** [comment]
Hey @Vimos 
Thanks for replying.
I ran your repo. However, I get the following error:
```
Traceback (most recent call last):
  File "/home/aneeshyjoshi/miniconda3/envs/gensim_env/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/aneeshyjoshi/miniconda3/envs/gensim_env/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/aneeshyjoshi/bi-att-flow/basic/cli.py", line 5, in <module>
    from basic.main import main as m
  File "/home/aneeshyjoshi/bi-att-flow/basic/main.py", line 14, in <module>
    from basic.model import get_multi_gpu_models
  File "/home/aneeshyjoshi/bi-att-flow/basic/model.py", line 10, in <module>
    from my.tensorflow.nn import softsel, get_logits, highway_network, multi_conv1d
  File "/home/aneeshyjoshi/bi-att-flow/my/tensorflow/nn.py", line 1, in <module>
    from tensorflow.python.ops.rnn_cell import _linear
ImportError: cannot import name '_linear'
```

It's the same problem I faced while porting. I couldn't find any replacement for the `_linear` function. Even the old copied definition of `_linear` doesn't seem to solve it.

But you were able to run it. Am I missing something?

**Comment by Vimos** [comment]
@aneesh-joshi , try the tf1.8 branch, not the master branch.

**Comment by aneesh-joshi** [comment]
@Vimos 
Thanks a lot!
(Like you said, I forgot to change branches)
It's working. 

Maybe you could make a PR to the original repo. It will be useful for everybody.
Also, did you make any ChangeLog with the changes (any functionality you had to give up on for the newer version). I am reading the diff, but a shorted log would be easier.

**Comment by Vimos** [comment]
@aneesh-joshi Glad that it's helping! 
The official repo has a `dev` branch which contains modifications to be compatible with `>Tf1.0`. Although I pulled their code, there are still some conflicts among different versions of TF. Since the repo is not actively maintained, I am not quite sure which branch to make the PR.

**Comment by JaneShenYY** [comment]
In nn.py:
replace
`from tensorflow.python.ops.rnn_cell_impl import _linear`
with
`from tensorflow.contrib.rnn.python.ops.core_rnn_cell import _linear`

replace
`flat_out = _linear(flat_args, output_size, bias, bias_start=bias_start, scope=scope`
with
`    with tf.variable_scope(scope or 'Linear'):
        flat_out = _linear(flat_args, output_size, bias, bias_initializer=tf.constant_initializer(bias_start))`

You can refer to the [code](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/contrib/rnn/python/ops/core_rnn_cell.py) to read the _linear() function.
