### ISSUE TITLE
absl.flags._exceptions.UnrecognizedFlagError: Unknown command line flag 'new_emb_mat'

### ISSUE THREAD

**Issue by yexing514** [allenai/bi-att-flow#96]
I am trying to get the repo working in TF1.7. I was able to get the training done with the help of dev branch for TF 1.4. But I failed in testing.  If I set it flags.DEFINE_integer("new_emb_mat", 0, "embedding matrix"), I got result F1 0.74 and accuracy 0.629. Is it normal? What value should we pass to new_emb_mat?

The error I got originally was :

Traceback (most recent call last):
  File "/anaconda/envs/py35/lib/python3.5/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/anaconda/envs/py35/lib/python3.5/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/adminye/bi-att-flow/basic/cli.py", line 128, in <module>
    tf.app.run()
  File "/anaconda/envs/py35/lib/python3.5/site-packages/tensorflow/python/platform/app.py", line 126, in run
    _sys.exit(main(argv))
  File "/home/adminye/bi-att-flow/basic/cli.py", line 125, in main
    m(config)
  File "/home/adminye/bi-att-flow/basic/main.py", line 26, in main
    _test(config)
  File "/home/adminye/bi-att-flow/basic/main.py", line 143, in _test
    config.new_emb_mat = new_emb_mat
  File "/anaconda/envs/py35/lib/python3.5/site-packages/tensorflow/python/platform/flags.py", line 88, in __setattr__
    return self.__dict__['__wrapped'].__setattr__(name, value)
  File "/anaconda/envs/py35/lib/python3.5/site-packages/absl/flags/_flagvalues.py", line 496, in __setattr__
    return self._set_unknown_flag(name, value)
  File "/anaconda/envs/py35/lib/python3.5/site-packages/absl/flags/_flagvalues.py", line 374, in _set_unknown_flag
    raise _exceptions.UnrecognizedFlagError(name, value)
absl.flags._exceptions.UnrecognizedFlagError: Unknown command line flag 'new_emb_mat'

**Comment by kumsantosh** [comment]
flags.DEFINE_integer("new_emb_mat", 0, "new_emb_mat")

**Comment by JaneShenYY** [comment]
> flags.DEFINE_integer("new_emb_mat", 0, "new_emb_mat")

add it into basic\cli.py file.

**Comment by JaneShenYY** [comment]
> flags.DEFINE_integer("new_emb_mat", 0, "new_emb_mat")

He asked What value should we pass to new_emb_mat?
